apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: github-runner-api-sa
      automountServiceAccountToken: true
      image: summerwind/actions-runner-dind
      repository: amerkul/account-service
      labels:
      - "actions_runner_dev"
      workVolumeClaimTemplate:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
