spring:
  elasticsearch:
    rest:
      uris: ${ELASTIC_HOST}:9200
  application:
    name: account
  liquibase:
    url: jdbc:${POSTGRES_HOST}://${POSTGRES_DOMAIN}:5432/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yml
  r2dbc:
    url: r2dbc:${POSTGRES_HOST}://${POSTGRES_DOMAIN}:5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    name: ${POSTGRES_DB}
  kafka:
    topics:
      bid: bidTopic
      answer: answerTopic
    bootstrap-servers: ${HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: reactivekafkagroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            value:
              default:
                type: com.example.account.domain.command.UpdateAccountCommand
logging:
  level:
    org.springframework.web: WARN
    com.example: DEBUG
server:
  port: 8080

