apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auction
  name: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
        - env:
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE
                  name: auction-env
            - name: DATABASESERVER_PORT
              value: "27017"
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: auction-env
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: auction-env
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: secret
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: auction-env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: auction-env
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  key: USERNAME
                  name: secret
          image: amerkul/auction-service:latest
          name: auction
          ports:
            - containerPort: 8081
      restartPolicy: Always
