apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: account-db
  name: account-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-db
  serviceName: "db"
  template:
    metadata:
      labels:
        app: account-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: accounts
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: account-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: account-secret
          image: postgres:14.5
          name: account-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: account
      restartPolicy: Always
      volumes:
        - name: account
          persistentVolumeClaim:
            claimName: account
