name: Publish Docker Image

on:
  push:
    branches: [istio-k8s]

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Try the cluster !
      run: kubectl get pods -A    
    - name: Deploy to minikube
      run:
        kubectl apply -f src/infra
