name: Publish Docker Image

on:
  push:
    branches: [istio-k8s]

jobs:
  deployment:

    runs-on:
      - self-hosted
      - actions_runner_dev

    steps:
    - uses: actions/checkout@v3  
    - name: Deploy to minikube
      run: |
          set -ex
          cd $HOME
          wget https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl apply -f src/infra -w
